@extends('layouts.app', ['title' => 'Presupuesto'])
@section('content')
<p class="eyebrow mb-2">Plan mensual</p>
<h1 class="display-title mb-1">Mi presupuesto</h1>
<p class="text-secondary mb-4">Compara lo planeado, lo gastado y lo proyectado.</p>
@if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if ($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('app.presupuestos.store') }}" class="card border-0 shadow-sm rounded-4 p-3 mb-4 vstack gap-3">@csrf
    <div class="row g-3"><div class="col-6"><label class="form-label">Año</label><input name="anio" type="number" min="2020" max="2100" value="{{ old('anio', now()->year) }}" class="form-control" required></div><div class="col-6"><label class="form-label">Mes</label><select name="mes" class="form-select" required>@foreach(range(1,12) as $mes)<option value="{{ $mes }}" @selected(old('mes', now()->month) == $mes)>{{ \Carbon\Carbon::create()->month($mes)->locale('es')->monthName }}</option>@endforeach</select></div></div>
    <div><label class="form-label">Alertar al alcanzar (%)</label><div class="d-flex flex-wrap gap-3">@foreach([70,80,90,100] as $umbral)<label class="form-check"><input class="form-check-input" type="checkbox" name="umbrales[]" value="{{ $umbral }}" @checked(in_array($umbral, old('umbrales', $presupuesto?->umbrales_alerta ?? [70,80,90,100])))> {{ $umbral }}%</label>@endforeach</div></div>
    <div class="vstack gap-2"><label class="form-label">Categorías y monto presupuestado</label>@foreach($categorias as $categoria)@php($lineaExistente = $presupuesto?->lineas->firstWhere('categoria_id', $categoria->id))<div class="input-group"><span class="input-group-text flex-grow-1">{{ $categoria->nombre }}</span><input name="lineas[]" type="text" data-miles inputmode="decimal" class="form-control" value="{{ old('lineas.'. $loop->index, $lineaExistente ? \App\Support\Dinero::centavosAPesos($lineaExistente->tope_centavos) : '') }}" placeholder="$ 0"><input type="hidden" name="categoria_ids[]" value="{{ $categoria->id }}"></div>@endforeach</div>
    <button class="btn btn-primary btn-lg rounded-4" type="submit">Guardar presupuesto</button>
</form>
@if($presupuesto)<h2 class="h5 mb-3">Seguimiento de {{ \Carbon\Carbon::create($presupuesto->anio, $presupuesto->mes)->locale('es')->monthName }}</h2><div class="vstack gap-2">@foreach($presupuesto->lineas as $linea)<article class="account-card"><div class="account-card__icon">%</div><div class="account-card__body"><div class="d-flex justify-content-between"><div><h2>{{ $linea->categoria->nombre }}</h2><small>Presupuesto @cop($linea->tope_centavos)</small></div><strong>@cop($linea->gasto_real_centavos)</strong></div><div class="small text-secondary mt-1">Real vs proyección: @cop($linea->gasto_real_centavos) · @cop($linea->proyeccion_centavos) · {{ $linea->porcentaje_consumido }}%</div>@if($linea->alertas)<div class="small text-danger mt-1">Alertas alcanzadas: {{ implode('%, ', $linea->alertas) }}%</div>@endif</div></article>@endforeach</div>@else<div class="alert alert-light">Aún no hay presupuesto para el mes actual.</div>@endif
@endsection
