<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PwaAssetController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SituacionController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CuentaLiquidaController;
use App\Http\Controllers\IngresoController;
use App\Http\Controllers\GastoController;
use App\Http\Controllers\DeudaController;
use App\Http\Controllers\TarjetaController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\PresupuestoController;
use App\Http\Controllers\MetaAhorroController;
use App\Http\Controllers\CalendarioController;
use App\Http\Controllers\ProyeccionController;

Route::get('/manifest.json', [PwaAssetController::class, 'manifest']);
Route::get('/sw.js', [PwaAssetController::class, 'serviceWorker']);
Route::get('/offline.html', [PwaAssetController::class, 'offline']);

// Route::get incluye HEAD (curl -I, probes). POST por si DirectoryIndex manda raro.
Route::get('/', HomeController::class)->name('home');
Route::post('/', HomeController::class);
Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('auth.login');
    Route::get('/registro', [AuthController::class, 'registerForm'])->name('register');
    Route::post('/registro', [AuthController::class, 'register'])->middleware('throttle:register')->name('auth.register');
});
Route::middleware('auth')->group(function (): void {
    Route::get('/situacion', SituacionController::class)->name('app.situacion');
    Route::get('/cuentas', [CuentaLiquidaController::class, 'index'])->name('app.cuentas.index');
    Route::get('/cuentas/crear', [CuentaLiquidaController::class, 'create'])->name('app.cuentas.create');
    Route::post('/cuentas', [CuentaLiquidaController::class, 'store'])->name('app.cuentas.store');
    Route::get('/cuentas/{cuenta}', [CuentaLiquidaController::class, 'show'])->name('app.cuentas.show');
    Route::get('/cuentas/{cuenta}/editar', [CuentaLiquidaController::class, 'edit'])->name('app.cuentas.edit');
    Route::put('/cuentas/{cuenta}', [CuentaLiquidaController::class, 'update'])->name('app.cuentas.update');
    Route::delete('/cuentas/{cuenta}', [CuentaLiquidaController::class, 'destroy'])->name('app.cuentas.destroy');
    Route::post('/cuentas/{cuenta}/restaurar', [CuentaLiquidaController::class, 'restore'])->name('app.cuentas.restore');
    Route::post('/cuentas/{cuenta}/cancelar', [CuentaLiquidaController::class, 'cancelar'])->name('app.cuentas.cancelar');
    Route::get('/ingresos', [IngresoController::class, 'index'])->name('app.ingresos.index');
    Route::get('/ingresos/crear', [IngresoController::class, 'create'])->name('app.ingresos.create');
    Route::post('/ingresos', [IngresoController::class, 'store'])->name('app.ingresos.store');
    Route::post('/ingresos/{hecho}/corregir', [IngresoController::class, 'corregir'])->name('app.ingresos.corregir');
    Route::get('/gastos', [GastoController::class, 'index'])->name('app.gastos.index');
    Route::get('/gastos/crear', [GastoController::class, 'create'])->name('app.gastos.create');
    Route::post('/gastos', [GastoController::class, 'store'])->name('app.gastos.store');
    Route::post('/gastos/{hecho}/corregir', [GastoController::class, 'corregir'])->name('app.gastos.corregir');
    Route::get('/deudas', [DeudaController::class, 'index'])->name('app.deudas.index');
    Route::get('/deudas/crear', [DeudaController::class, 'create'])->name('app.deudas.create');
    Route::post('/deudas', [DeudaController::class, 'store'])->name('app.deudas.store');
    Route::post('/deudas/pagos', [DeudaController::class, 'pagar'])->name('app.deudas.pagos.store');
    Route::post('/deudas/pagos/{pago}/corregir', [DeudaController::class, 'corregirPago'])->name('app.deudas.pagos.corregir');
    Route::get('/tarjetas', [TarjetaController::class, 'index'])->name('app.tarjetas.index');
    Route::get('/tarjetas/crear', [TarjetaController::class, 'create'])->name('app.tarjetas.create');
    Route::post('/tarjetas', [TarjetaController::class, 'store'])->name('app.tarjetas.store');
    Route::post('/tarjetas/compras', [TarjetaController::class, 'compra'])->name('app.tarjetas.compras.store');
    Route::post('/tarjetas/compras/{compra}/corregir', [TarjetaController::class, 'corregirCompra'])->name('app.tarjetas.compras.corregir');
    Route::post('/tarjetas/pagos', [TarjetaController::class, 'pagar'])->name('app.tarjetas.pagos.store');
    Route::post('/tarjetas/pagos/{pago}/corregir', [TarjetaController::class, 'corregirPago'])->name('app.tarjetas.pagos.corregir');
    Route::get('/pagos', [PagoController::class, 'index'])->name('app.pagos.index');
    Route::post('/pagos', [PagoController::class, 'store'])->name('app.pagos.store');
    Route::post('/pagos/{pago}/corregir', [PagoController::class, 'corregirPago'])->name('app.pagos.corregir');
    Route::post('/transferencias', [PagoController::class, 'transferir'])->name('app.transferencias.store');
    Route::post('/transferencias/{hecho}/corregir', [PagoController::class, 'corregirTransferencia'])->name('app.transferencias.corregir');
    Route::get('/presupuestos', [PresupuestoController::class, 'index'])->name('app.presupuestos.index');
    Route::post('/presupuestos', [PresupuestoController::class, 'store'])->name('app.presupuestos.store');
    Route::post('/categorias', [PresupuestoController::class, 'storeCategoria'])->name('app.categorias.store');
    Route::put('/categorias/{categoria}', [PresupuestoController::class, 'updateCategoria'])->name('app.categorias.update');
    Route::get('/metas', [MetaAhorroController::class, 'index'])->name('app.metas.index');
    Route::post('/metas', [MetaAhorroController::class, 'store'])->name('app.metas.store');
    Route::put('/metas/{meta}', [MetaAhorroController::class, 'update'])->name('app.metas.update');
    Route::post('/metas/aportes', [MetaAhorroController::class, 'aportar'])->name('app.metas.aportes.store');
    Route::post('/metas/retiros', [MetaAhorroController::class, 'retirar'])->name('app.metas.retiros.store');
    Route::post('/metas/movimientos/{hecho}/corregir', [MetaAhorroController::class, 'corregir'])->name('app.metas.movimientos.corregir');
    Route::get('/calendario', CalendarioController::class)->name('app.calendario');
    Route::get('/proyecciones', ProyeccionController::class)->name('app.proyecciones');
    Route::post('/logout', [AuthController::class, 'logout'])->name('auth.logout');
});
