@extends('layouts.app', ['title' => 'Deudas'])
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><p class="eyebrow mb-2">Obligaciones</p><h1 class="display-title mb-1">Mis deudas</h1><p class="text-secondary mb-0">Todo lo que debes, con claridad.</p></div><a class="add-button" href="{{ route('app.deudas.create') }}">+</a></div>
@if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
<div class="vstack gap-3">
@foreach($prestamos as $deuda)<article class="account-card"><div class="account-card__icon">↘</div><div class="account-card__body"><div class="d-flex justify-content-between"><div><h2>{{ $deuda->nombre }}</h2><small>{{ $deuda->entidad ?: 'Obligación' }} · {{ str_replace('_', ' ', $deuda->tipo_obligacion) }}</small></div><strong>@cop($deuda->saldo_actual_centavos)</strong></div><div class="debt-meta"><span>{{ $deuda->cuotas_pagadas }} pagadas</span><span>{{ $deuda->cuotas_pendientes }} pendientes</span><span class="status-pill">{{ ucfirst($deuda->estado) }}</span></div><details class="mt-2"><summary class="small text-primary">Ver cronograma</summary><div class="table-responsive mt-2"><table class="table table-sm small"><thead><tr><th>Cuota</th><th>Fecha</th><th>Capital</th><th>Interés</th><th>Otros</th><th>Total</th><th>Saldo</th></tr></thead><tbody>@foreach($deuda->cuotas as $cuota)<tr><td>{{ $cuota->numero }}</td><td>{{ $cuota->fecha_vencimiento->format('d/m/Y') }}</td><td>@cop($cuota->capital_centavos)</td><td>@cop($cuota->interes_centavos)</td><td>@cop($cuota->seguro_centavos + $cuota->otros_cargos_centavos)</td><td>@cop($cuota->total_centavos)</td><td>@cop($cuota->saldo_capital_centavos)</td></tr>@endforeach</tbody></table></div></details></div></article>@endforeach
@foreach($tarjetas as $deuda)<article class="account-card"><div class="account-card__icon">▣</div><div class="account-card__body"><div class="d-flex justify-content-between"><div><h2>{{ $deuda->nombre }}</h2><small>{{ $deuda->entidad ?: 'Tarjeta de crédito' }}</small></div><strong>@cop($deuda->saldo_actual_centavos)</strong></div><div class="debt-meta"><span>Cupo @cop($deuda->cupo_centavos)</span><span>{{ $deuda->cuotas_pendientes }} pendientes</span><span class="status-pill">{{ ucfirst($deuda->estado) }}</span></div></div></article>@endforeach
@if($prestamos->isEmpty() && $tarjetas->isEmpty())<div class="alert alert-light">Aún no tienes obligaciones registradas.</div>@endif
</div>
@endsection
